import type { AdditionFramework, Claim, GenealogyEdge, GenealogyNode, Source } from './types.js';

const sources: Source[] = [
  {
    id: 'blavatsky-secret-doctrine',
    title: 'The Secret Doctrine',
    author: 'H. P. Blavatsky',
    date: '1888',
    url: 'https://www.theosociety.org/pasadena/sd/sd-hp.htm',
    sourceType: 'primary esoteric',
    summary:
      'A foundational Theosophical text that uses akasha and related concepts inside a broader esoteric cosmology.',
    confidenceLevel: 'high',
    citationNotes: 'Use as primary esoteric material; distinguish textual content from historical verification.',
  },
  {
    id: 'steiner-akashic-record',
    title: 'Cosmic Memory: Prehistory of Earth and Man',
    author: 'Rudolf Steiner',
    date: '1904-1908',
    url: 'https://rsarchive.org/Books/GA011/',
    sourceType: 'primary esoteric',
    summary:
      'Anthroposophical lectures and essays describing access to an Akashic record as spiritual-scientific testimony.',
    confidenceLevel: 'high',
    citationNotes: 'Treat as primary Anthroposophical testimony, not empirical evidence.',
  },
  {
    id: 'jung-collective-unconscious',
    title: 'The Archetypes and the Collective Unconscious',
    author: 'C. G. Jung',
    date: '1959',
    url: 'https://press.princeton.edu/books/paperback/9780691018331/the-archetypes-and-the-collective-unconscious',
    sourceType: 'academic',
    summary:
      'Psychological framework often compared with universal-memory ideas, though it is not an Akashic Records source.',
    confidenceLevel: 'medium',
    citationNotes: 'Use only for comparative psychological interpretation.',
  },
  {
    id: 'cayce-readings',
    title: 'Edgar Cayce Reading Collections',
    author: 'Association for Research and Enlightenment',
    date: '20th century',
    url: 'https://www.edgarcayce.org/',
    sourceType: 'modern spiritual',
    summary:
      'Modern spiritual material containing experiential claims about readings and access to nonordinary information.',
    confidenceLevel: 'medium',
    citationNotes: 'Classify as modern spiritual testimony unless corroborated by independent historical sources.',
  },
  {
    id: 'britannica-akashic-record',
    title: 'Akashic record',
    author: 'Encyclopaedia Britannica',
    date: 'reference entry',
    url: 'https://www.britannica.com/topic/Akashic-record',
    sourceType: 'historical',
    summary:
      'Concise reference entry describing the Akashic record as an occult concept rather than an empirically verified archive.',
    confidenceLevel: 'medium',
    citationNotes: 'Useful for neutral definition and public-facing summary language.',
  },
  {
    id: 'encyclopedia-akashic-records',
    title: 'Akashic Records',
    author: 'Encyclopedia.com',
    date: 'reference entry',
    url: 'https://www.encyclopedia.com/science/encyclopedias-almanacs-transcripts-and-maps/akashic-records',
    sourceType: 'historical',
    summary:
      'Reference overview that situates Akashic Records in occult and modern spiritual contexts, including Cayce-related material.',
    confidenceLevel: 'medium',
    citationNotes: 'Use as secondary reference; verify named movement claims against primary sources.',
  },
  {
    id: 'theosophy-wiki-akashic-records',
    title: 'Akashic Records',
    author: 'Theosophy Wiki',
    date: 'reference article',
    url: 'https://theosophy.wiki/en/Akashic_Records',
    sourceType: 'primary esoteric',
    summary:
      'Movement-oriented reference gathering Theosophical definitions and descriptions of record-reading claims.',
    confidenceLevel: 'medium',
    citationNotes: 'Good lead source for Theosophical terminology; verify quoted primary texts before final citation.',
  },
  {
    id: 'sinnett-esoteric-buddhism',
    title: 'Esoteric Buddhism',
    author: 'A. P. Sinnett',
    date: '1883',
    url: 'https://archive.org/details/esotericbuddhism00sinn',
    sourceType: 'primary esoteric',
    summary:
      'Early Theosophical book that helped transmit occultized Buddhist and esoteric cosmological vocabulary into Western readership.',
    confidenceLevel: 'medium',
    citationNotes: 'Use for historical lineage, with care around colonial-era and Theosophical framing.',
  },
  {
    id: 'olcott-buddhist-catechism',
    title: 'The Buddhist Catechism',
    author: 'Henry S. Olcott',
    date: '1881',
    url: 'https://archive.org/details/buddhistcatechis00olco',
    sourceType: 'religious/comparative',
    summary:
      'Theosophical-era Buddhist catechism relevant to tracing terms and ideas cited in later Akashic-record histories.',
    confidenceLevel: 'medium',
    citationNotes: 'Use as historical context, not as a direct Akashic Records source.',
  },
  {
    id: 'leadbeater-akashic-records',
    title: 'The Akashic Records',
    author: 'C. W. Leadbeater',
    date: 'early 20th century',
    url: 'https://www.cwlworld.info/The_Akashic_Records_c.pdf',
    sourceType: 'primary esoteric',
    summary:
      'Leadbeater text giving a Theosophical account of record-reading and planes of perception.',
    confidenceLevel: 'medium',
    citationNotes: 'Treat as primary esoteric testimony and doctrine, not independent historical evidence.',
  },
  {
    id: 'besant-leadbeater-man',
    title: 'Man: Whence, How and Whither',
    author: 'Annie Besant and C. W. Leadbeater',
    date: '1913',
    url: 'https://archive.org/details/manwhencehowandw031919mbp',
    sourceType: 'primary esoteric',
    summary:
      'Theosophical clairvoyant-investigation text that exemplifies record-access claims about human origins and prehistory.',
    confidenceLevel: 'medium',
    citationNotes: 'Use as primary source for claims made by authors; separate from historical verification.',
  },
  {
    id: 'are-akashic-records',
    title: 'Edgar Cayce on the Akashic Records',
    author: 'Edgar Cayce Association for Research and Enlightenment',
    date: 'modern archive page',
    url: 'https://edgarcayce.org/edgar-cayce/readings/akashic-records/',
    sourceType: 'modern spiritual',
    summary:
      'A.R.E. page presenting Cayce movement explanations of Akashic Records and the Book of Life framing.',
    confidenceLevel: 'medium',
    citationNotes: 'Use for Cayce movement self-description and reading excerpts.',
  },
  {
    id: 'cayce-personal-growth',
    title: 'Edgar Cayce, the Akashic Records and Personal Growth',
    author: 'Edgar Cayce Association for Research and Enlightenment',
    date: '2017',
    url: 'https://content.edgarcayce.org/about-us/blog/blog-posts/edgar-cayce-the-akashic-records-and-personal-growth/',
    sourceType: 'modern spiritual',
    summary:
      'Modern A.R.E. article connecting Akashic-record ideas to personal growth and life-review language.',
    confidenceLevel: 'medium',
    citationNotes: 'Classify as contemporary movement interpretation.',
  },
  {
    id: 'aquarian-gospel',
    title: 'The Aquarian Gospel of Jesus the Christ',
    author: 'Levi H. Dowling',
    date: '1908',
    url: 'https://archive.org/details/aquariangospelo00dowlgoog',
    sourceType: 'modern spiritual',
    summary:
      'Early twentieth-century New Thought text presented as material accessed from Akashic Records.',
    confidenceLevel: 'medium',
    citationNotes: 'Use as example of claimed Akashic transcription in modern spiritual literature.',
  },
  {
    id: 'britannica-akasha-jainism',
    title: 'Akasha',
    author: 'Encyclopaedia Britannica',
    date: 'reference entry',
    url: 'https://www.britannica.com/topic/akasha-Jainism',
    sourceType: 'religious/comparative',
    summary:
      'Reference entry on akasha in Jain context, useful for distinguishing South Asian term-history from Western occult usage.',
    confidenceLevel: 'medium',
    citationNotes: 'Use for comparative terminology, not for Akashic Records claims.',
  },
  {
    id: 'akasha-wikipedia',
    title: 'Akasha',
    author: 'Wikipedia contributors',
    date: 'reference article',
    url: 'https://en.wikipedia.org/wiki/Akasha',
    sourceType: 'religious/comparative',
    summary:
      'General reference article on akasha across Indian religious and philosophical contexts.',
    confidenceLevel: 'low',
    citationNotes: 'Use as lead-finding only; prefer cited primary or academic sources for final research.',
  },
  {
    id: 'akashic-records-wikipedia',
    title: 'Akashic records',
    author: 'Wikipedia contributors',
    date: 'reference article',
    url: 'https://en.wikipedia.org/wiki/Akashic_records',
    sourceType: 'historical',
    summary:
      'General reference article linking Theosophy, Steiner, Cayce, and modern popular usage.',
    confidenceLevel: 'low',
    citationNotes: 'Use as a map of leads and references, not as final authority.',
  },
];

const claims: Claim[] = [
  {
    id: 'claim-theosophy-akasha',
    sourceId: 'blavatsky-secret-doctrine',
    text: 'Theosophical literature made akasha a central concept in an esoteric cosmology during the late nineteenth century.',
    type: 'historical claim',
    evidenceGrade: 'A',
    confidenceLevel: 'high',
    citationRequired: true,
    notes: 'Historically documentable as a publication and movement claim.',
  },
  {
    id: 'claim-steiner-access',
    sourceId: 'steiner-akashic-record',
    text: 'Steiner presented Akashic-record readings as spiritual research rather than conventional historical method.',
    type: 'experiential claim',
    evidenceGrade: 'D',
    confidenceLevel: 'high',
    citationRequired: true,
    notes: 'Accurately describes the source position; does not validate the asserted access.',
  },
  {
    id: 'claim-jung-analogue',
    sourceId: 'jung-collective-unconscious',
    text: 'The collective unconscious can be compared to Akashic Records ideas as a psychological analogue, not as the same doctrine.',
    type: 'psychological interpretation',
    evidenceGrade: 'C',
    confidenceLevel: 'medium',
    citationRequired: true,
    notes: 'Comparative framing requires careful wording and citations to both traditions.',
  },
  {
    id: 'claim-cayce-testimony',
    sourceId: 'cayce-readings',
    text: 'Cayce-related materials contain subjective reports of access to records or readings beyond ordinary memory.',
    type: 'experiential claim',
    evidenceGrade: 'D',
    confidenceLevel: 'medium',
    citationRequired: true,
    notes: 'Treat as testimony and movement history, not empirical proof.',
  },
  {
    id: 'claim-britannica-occult-definition',
    sourceId: 'britannica-akashic-record',
    text: 'Reference works describe the Akashic record as an occult concept rather than a verified empirical archive.',
    type: 'historical claim',
    evidenceGrade: 'B',
    confidenceLevel: 'medium',
    citationRequired: true,
    notes: 'Useful neutral baseline for public-facing definitions.',
  },
  {
    id: 'claim-theosophy-lineage',
    sourceId: 'theosophy-wiki-akashic-records',
    text: 'Theosophical writers developed detailed accounts of record-reading through concepts of subtle planes and clairvoyant perception.',
    type: 'historical claim',
    evidenceGrade: 'B',
    confidenceLevel: 'medium',
    citationRequired: true,
    notes: 'Verify specific quotations against Leadbeater, Besant, Sinnett, or other primary texts.',
  },
  {
    id: 'claim-sinnett-transmission',
    sourceId: 'sinnett-esoteric-buddhism',
    text: 'Late nineteenth-century Theosophical literature helped transmit esoteric cosmology into Western occult readership.',
    type: 'historical claim',
    evidenceGrade: 'B',
    confidenceLevel: 'medium',
    citationRequired: true,
    notes: 'Use for intellectual genealogy rather than direct proof of Akashic Records.',
  },
  {
    id: 'claim-leadbeater-record-reading',
    sourceId: 'leadbeater-akashic-records',
    text: 'Leadbeater presented Akashic Records as accessible through trained clairvoyant perception within a Theosophical cosmology.',
    type: 'experiential claim',
    evidenceGrade: 'D',
    confidenceLevel: 'medium',
    citationRequired: true,
    notes: 'Accurately describes the source claim while leaving validity unverified.',
  },
  {
    id: 'claim-besant-leadbeater-prehistory',
    sourceId: 'besant-leadbeater-man',
    text: 'Besant and Leadbeater used clairvoyant investigation to construct esoteric narratives of human origins and prehistory.',
    type: 'experiential claim',
    evidenceGrade: 'D',
    confidenceLevel: 'medium',
    citationRequired: true,
    notes: 'Primary esoteric account; compare with historical scholarship before interpretation.',
  },
  {
    id: 'claim-cayce-book-of-life',
    sourceId: 'are-akashic-records',
    text: 'Cayce-related materials connect Akashic Records language with the Book of Life and individual soul history.',
    type: 'experiential claim',
    evidenceGrade: 'D',
    confidenceLevel: 'medium',
    citationRequired: true,
    notes: 'Classify as Cayce movement teaching and reading interpretation.',
  },
  {
    id: 'claim-aquarian-gospel-akashic',
    sourceId: 'aquarian-gospel',
    text: 'The Aquarian Gospel represents an early modern spiritual text framed as material received from Akashic Records.',
    type: 'historical claim',
    evidenceGrade: 'B',
    confidenceLevel: 'medium',
    citationRequired: true,
    notes: 'Historically documentable publication claim; does not validate the claimed access method.',
  },
  {
    id: 'claim-akasha-distinction',
    sourceId: 'britannica-akasha-jainism',
    text: 'Akasha has South Asian philosophical meanings that should not be collapsed into Western Akashic Records doctrine.',
    type: 'symbolic interpretation',
    evidenceGrade: 'C',
    confidenceLevel: 'medium',
    citationRequired: true,
    notes: 'Important terminology guardrail for comparative research.',
  },
  {
    id: 'claim-wikipedia-lead-map',
    sourceId: 'akashic-records-wikipedia',
    text: 'General reference articles are useful lead maps but should be replaced by primary or specialist sources in final citations.',
    type: 'historical claim',
    evidenceGrade: 'C',
    confidenceLevel: 'high',
    citationRequired: false,
    notes: 'Workflow rule for corpus hygiene.',
  },
];

const nodes: GenealogyNode[] = [
  {
    id: 'akasha',
    label: 'Akasha',
    period: 'Classical and premodern South Asian contexts',
    category: 'religious/comparative',
    description: 'A Sanskrit term often translated as ether, space, or subtle element depending on context.',
  },
  {
    id: 'theosophy',
    label: 'Theosophy',
    period: 'Late 19th century',
    category: 'primary esoteric',
    description: 'Popularized esoteric uses of akasha in Western occult and comparative-religion settings.',
  },
  {
    id: 'anthroposophy',
    label: 'Anthroposophy',
    period: 'Early 20th century',
    category: 'primary esoteric',
    description: 'Developed Akashic-record language through Steiner’s spiritual research claims.',
  },
  {
    id: 'cayce',
    label: 'Edgar Cayce movement',
    period: '20th century',
    category: 'modern spiritual',
    description: 'Associated Akashic Records with readings, reincarnation narratives, and spiritual counseling.',
  },
  {
    id: 'jung',
    label: 'Collective unconscious analogue',
    period: '20th century',
    category: 'psychological interpretation',
    description: 'A comparative psychological model sometimes used as an analogue, with important limits.',
  },
  {
    id: 'information-field',
    label: 'Information-field speculation',
    period: 'Late 20th to 21st century',
    category: 'speculative',
    description: 'Modern speculative framing that treats Akashic Records as a mythic data-field concept.',
  },
  {
    id: 'sinnett',
    label: 'A. P. Sinnett',
    period: 'Late 19th century',
    category: 'primary esoteric',
    description: 'Theosophical author whose work helped popularize esoteric cosmology in English-language occultism.',
  },
  {
    id: 'leadbeater-besant',
    label: 'Leadbeater and Besant clairvoyant histories',
    period: 'Early 20th century',
    category: 'primary esoteric',
    description: 'Theosophical writings that present record-style clairvoyant investigations of hidden history.',
  },
  {
    id: 'book-of-life',
    label: 'Book of Life motif',
    period: 'Biblical and modern spiritual reinterpretations',
    category: 'religious/comparative',
    description: 'A comparative motif used in Cayce-related explanations of Akashic Records.',
  },
  {
    id: 'new-thought',
    label: 'New Thought and modern metaphysical publishing',
    period: 'Late 19th to early 20th century',
    category: 'modern spiritual',
    description: 'Publishing context for texts claiming access to hidden spiritual records or higher planes.',
  },
];

const edges: GenealogyEdge[] = [
  { from: 'akasha', to: 'theosophy', label: 'term adapted into Western esoteric synthesis', confidence: 'medium' },
  { from: 'theosophy', to: 'anthroposophy', label: 'conceptual inheritance and reinterpretation', confidence: 'high' },
  { from: 'anthroposophy', to: 'cayce', label: 'parallel modern spiritual record-access motif', confidence: 'low' },
  { from: 'jung', to: 'information-field', label: 'psychological analogy used in later theory building', confidence: 'medium' },
  { from: 'cayce', to: 'information-field', label: 'modern spiritual testimony recast as information metaphor', confidence: 'medium' },
  { from: 'theosophy', to: 'sinnett', label: 'popularization through English-language Theosophical publishing', confidence: 'medium' },
  { from: 'sinnett', to: 'leadbeater-besant', label: 'movement vocabulary expanded into clairvoyant histories', confidence: 'medium' },
  { from: 'leadbeater-besant', to: 'anthroposophy', label: 'parallel occult-historical record access claims', confidence: 'low' },
  { from: 'book-of-life', to: 'cayce', label: 'religious motif used in Cayce movement explanations', confidence: 'medium' },
  { from: 'new-thought', to: 'cayce', label: 'shared modern metaphysical publishing environment', confidence: 'low' },
];

const additionFrameworks: AdditionFramework[] = [
  {
    id: 'symbolic-memory',
    name: 'Symbolic universal memory',
    description: 'Treats the Akashic Records as a symbol for cultural memory and accumulated moral imagination.',
    requiredBoundaries: ['Mark as interpretive', 'Avoid empirical claims', 'Cite source traditions being compared'],
  },
  {
    id: 'consciousness-archive',
    name: 'Consciousness archive metaphor',
    description: 'Frames record language as a metaphor for how minds organize memory, meaning, and identity.',
    requiredBoundaries: ['Mark as metaphor', 'Separate psychology from metaphysics', 'Avoid claims of literal access'],
  },
  {
    id: 'information-persistence',
    name: 'Information persistence framework',
    description: 'Speculates about persistence of information as a mythic or philosophical lens, not a proven field.',
    requiredBoundaries: ['Mark as speculative', 'Do not cite physics as proof', 'Require explicit uncertainty language'],
  },
];

export const researchDataset = {
  sources,
  claims,
  genealogy: { nodes, edges },
  additionFrameworks,
};
